export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';


export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';

export const QUERY_PHOTOS_SUCCESS = 'QUERY_PHOTOS_SUCCESS';
export const QUERY_PHOTOS_FAIL = 'QUERY_PHOTOS_FAIL';

export const POST_PHOTO_SUCCESS = 'POST_PHOTO_SUCCESS';
export const POST_PHOTO_FAIL = 'POST_PHOTO_FAIL';

export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';




